// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBrpIk6Ug7JF41RwAY_AV--L8BtQ1lcFi8',
    appId: '1:17906073368:web:843f55c9e81227bd5ee86d',
    messagingSenderId: '17906073368',
    projectId: 'emirates-7a4fd',
    authDomain: 'emirates-7a4fd.firebaseapp.com',
    storageBucket: 'emirates-7a4fd.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA8SDk63MOUeDoEWJphiMacZ_wEh8wy6BU',
    appId: '1:17906073368:android:856f33e3326e36765ee86d',
    messagingSenderId: '17906073368',
    projectId: 'emirates-7a4fd',
    storageBucket: 'emirates-7a4fd.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBlOPYebsKfEwjBXM4dhPP3qkKBjXrlzNk',
    appId: '1:17906073368:ios:4bcbed42a1120da85ee86d',
    messagingSenderId: '17906073368',
    projectId: 'emirates-7a4fd',
    storageBucket: 'emirates-7a4fd.firebasestorage.app',
    iosBundleId: 'com.example.emirates',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBlOPYebsKfEwjBXM4dhPP3qkKBjXrlzNk',
    appId: '1:17906073368:ios:4bcbed42a1120da85ee86d',
    messagingSenderId: '17906073368',
    projectId: 'emirates-7a4fd',
    storageBucket: 'emirates-7a4fd.firebasestorage.app',
    iosBundleId: 'com.example.emirates',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBrpIk6Ug7JF41RwAY_AV--L8BtQ1lcFi8',
    appId: '1:17906073368:web:5053ea0d2e2ea5a15ee86d',
    messagingSenderId: '17906073368',
    projectId: 'emirates-7a4fd',
    authDomain: 'emirates-7a4fd.firebaseapp.com',
    storageBucket: 'emirates-7a4fd.firebasestorage.app',
  );
}
